version: "3.9"

services:
  web:
    build:
      context: ./apps/auth
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./apps/auth/.env
    depends_on:
      - db
  
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
    - ./apps/auth/database/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./apps/auth/database/migrations:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
    
      