name: Authentication Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Login on Docker
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.18.0
      - name: Install dependencies
        working-directory: ./apps/auth
        run: npm install
      - name: Run Tests
        working-directory: ./apps/auth
        run: npm test
      - name: Build Image
        working-directory: ./apps/auth
        run: docker build -t allcarsinone/auth_service:${{ github.sha }}
      - name: Push to Docker
        run: docker push allcarsinone/auth_service:${{ github.sha }}
        

  
